# The Docker image that will be used to build your app
image: "pages:   script:     - echo '<html><body>Hello World</body></html>' >
  public/index.html   artifacts:     paths:       - public/   rules:     - if:
  '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'       when: always"
